openapi: 3.0.0
info:
  title: Restaurant BES API
  version: 0.1.9

servers:
  - url: https://localhost
    description: Main server

paths:
  /echo:
    post:
      summary: Echo text

      requestBody:
        description: Echo text
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                text:
                  type: string
              required:
                - name
                - text
              example:
                name: Alice
                text: Hello world!

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  author:
                    type: string
                  text:
                    type: string
#                  time:
#                    type: string
        '400':
          description: Error

